//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDALService")]
public interface IDALService
{

    // CODEGEN: Parameter 'ExecuteDataSetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDALService/ExecuteDataSet", ReplyAction = "http://tempuri.org/IDALService/ExecuteDataSetResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SQLParameter[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SqlParameter[]))]
    ExecuteDataSetResponse ExecuteDataSet(ExecuteDataSetRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDALService/ExecuteDataSet", ReplyAction = "http://tempuri.org/IDALService/ExecuteDataSetResponse")]
    System.Threading.Tasks.Task<ExecuteDataSetResponse> ExecuteDataSetAsync(ExecuteDataSetRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDALService/ExecuteNonQueryOutput", ReplyAction = "http://tempuri.org/IDALService/ExecuteNonQueryOutputResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SQLParameter[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SqlParameter[]))]
    ExecuteNonQueryOutputResponse ExecuteNonQueryOutput(ExecuteNonQueryOutputRequest request);

    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDALService/ExecuteNonQueryOutput", ReplyAction = "http://tempuri.org/IDALService/ExecuteNonQueryOutputResponse")]
    System.Threading.Tasks.Task<ExecuteNonQueryOutputResponse> ExecuteNonQueryOutputAsync(ExecuteNonQueryOutputRequest request);

    // CODEGEN: Parameter 'commandText' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDALService/ExecuteNonQuery", ReplyAction = "http://tempuri.org/IDALService/ExecuteNonQueryResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SQLParameter[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SqlParameter[]))]
    ExecuteNonQueryResponse ExecuteNonQuery(ExecuteNonQueryRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDALService/ExecuteNonQuery", ReplyAction = "http://tempuri.org/IDALService/ExecuteNonQueryResponse")]
    System.Threading.Tasks.Task<ExecuteNonQueryResponse> ExecuteNonQueryAsync(ExecuteNonQueryRequest request);

    // CODEGEN: Parameter 'ExecuteScalarResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDALService/ExecuteScalar", ReplyAction = "http://tempuri.org/IDALService/ExecuteScalarResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SQLParameter[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SqlParameter[]))]
    ExecuteScalarResponse ExecuteScalar(ExecuteScalarRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDALService/ExecuteScalar", ReplyAction = "http://tempuri.org/IDALService/ExecuteScalarResponse")]
    System.Threading.Tasks.Task<ExecuteScalarResponse> ExecuteScalarAsync(ExecuteScalarRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerService")]
public partial class SQLParameter
{

    private ParameterDirection paramaterDirectionField;

    private bool paramaterDirectionFieldSpecified;

    private string paramaterNameField;

    private object paramaterValueField;

    private SqlDbType parameterTypeField;

    private bool parameterTypeFieldSpecified;

    private string sizeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public ParameterDirection ParamaterDirection
    {
        get
        {
            return this.paramaterDirectionField;
        }
        set
        {
            this.paramaterDirectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ParamaterDirectionSpecified
    {
        get
        {
            return this.paramaterDirectionFieldSpecified;
        }
        set
        {
            this.paramaterDirectionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
    public string ParamaterName
    {
        get
        {
            return this.paramaterNameField;
        }
        set
        {
            this.paramaterNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
    public object ParamaterValue
    {
        get
        {
            return this.paramaterValueField;
        }
        set
        {
            this.paramaterValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public SqlDbType ParameterType
    {
        get
        {
            return this.parameterTypeField;
        }
        set
        {
            this.parameterTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ParameterTypeSpecified
    {
        get
        {
            return this.parameterTypeFieldSpecified;
        }
        set
        {
            this.parameterTypeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
    public string Size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System.Data")]
public enum ParameterDirection
{

    /// <remarks/>
    Input,

    /// <remarks/>
    Output,

    /// <remarks/>
    InputOutput,

    /// <remarks/>
    ReturnValue,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DbParameter))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SqlParameter))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System")]
public partial class MarshalByRefObject
{

    private object @__identityField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
    public object @__identity
    {
        get
        {
            return this.@__identityField;
        }
        set
        {
            this.@__identityField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SqlParameter))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System.Data.Common")]
public partial class DbParameter : MarshalByRefObject
{

    private DbType dbTypeField;

    private bool dbTypeFieldSpecified;

    private ParameterDirection directionField;

    private bool directionFieldSpecified;

    private bool isNullableField;

    private bool isNullableFieldSpecified;

    private string parameterNameField;

    private byte precisionField;

    private bool precisionFieldSpecified;

    private byte scaleField;

    private bool scaleFieldSpecified;

    private int sizeField;

    private bool sizeFieldSpecified;

    private string sourceColumnField;

    private bool sourceColumnNullMappingField;

    private bool sourceColumnNullMappingFieldSpecified;

    private DataRowVersion sourceVersionField;

    private bool sourceVersionFieldSpecified;

    private object valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public DbType DbType
    {
        get
        {
            return this.dbTypeField;
        }
        set
        {
            this.dbTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DbTypeSpecified
    {
        get
        {
            return this.dbTypeFieldSpecified;
        }
        set
        {
            this.dbTypeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public ParameterDirection Direction
    {
        get
        {
            return this.directionField;
        }
        set
        {
            this.directionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DirectionSpecified
    {
        get
        {
            return this.directionFieldSpecified;
        }
        set
        {
            this.directionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public bool IsNullable
    {
        get
        {
            return this.isNullableField;
        }
        set
        {
            this.isNullableField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsNullableSpecified
    {
        get
        {
            return this.isNullableFieldSpecified;
        }
        set
        {
            this.isNullableFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
    public string ParameterName
    {
        get
        {
            return this.parameterNameField;
        }
        set
        {
            this.parameterNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public byte Precision
    {
        get
        {
            return this.precisionField;
        }
        set
        {
            this.precisionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrecisionSpecified
    {
        get
        {
            return this.precisionFieldSpecified;
        }
        set
        {
            this.precisionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public byte Scale
    {
        get
        {
            return this.scaleField;
        }
        set
        {
            this.scaleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ScaleSpecified
    {
        get
        {
            return this.scaleFieldSpecified;
        }
        set
        {
            this.scaleFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public int Size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeSpecified
    {
        get
        {
            return this.sizeFieldSpecified;
        }
        set
        {
            this.sizeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
    public string SourceColumn
    {
        get
        {
            return this.sourceColumnField;
        }
        set
        {
            this.sourceColumnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public bool SourceColumnNullMapping
    {
        get
        {
            return this.sourceColumnNullMappingField;
        }
        set
        {
            this.sourceColumnNullMappingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SourceColumnNullMappingSpecified
    {
        get
        {
            return this.sourceColumnNullMappingFieldSpecified;
        }
        set
        {
            this.sourceColumnNullMappingFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public DataRowVersion SourceVersion
    {
        get
        {
            return this.sourceVersionField;
        }
        set
        {
            this.sourceVersionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SourceVersionSpecified
    {
        get
        {
            return this.sourceVersionFieldSpecified;
        }
        set
        {
            this.sourceVersionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
    public object Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System.Data")]
public enum DbType
{

    /// <remarks/>
    AnsiString,

    /// <remarks/>
    Binary,

    /// <remarks/>
    Byte,

    /// <remarks/>
    Boolean,

    /// <remarks/>
    Currency,

    /// <remarks/>
    Date,

    /// <remarks/>
    DateTime,

    /// <remarks/>
    Decimal,

    /// <remarks/>
    Double,

    /// <remarks/>
    Guid,

    /// <remarks/>
    Int16,

    /// <remarks/>
    Int32,

    /// <remarks/>
    Int64,

    /// <remarks/>
    Object,

    /// <remarks/>
    SByte,

    /// <remarks/>
    Single,

    /// <remarks/>
    String,

    /// <remarks/>
    Time,

    /// <remarks/>
    UInt16,

    /// <remarks/>
    UInt32,

    /// <remarks/>
    UInt64,

    /// <remarks/>
    VarNumeric,

    /// <remarks/>
    AnsiStringFixedLength,

    /// <remarks/>
    StringFixedLength,

    /// <remarks/>
    Xml,

    /// <remarks/>
    DateTime2,

    /// <remarks/>
    DateTimeOffset,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System.Data")]
public enum DataRowVersion
{

    /// <remarks/>
    Original,

    /// <remarks/>
    Current,

    /// <remarks/>
    Proposed,

    /// <remarks/>
    Default,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System.Data.SqlClient")]
public partial class SqlParameter : DbParameter
{

    private SqlCompareOptions compareInfoField;

    private bool compareInfoFieldSpecified;

    private int localeIdField;

    private bool localeIdFieldSpecified;

    private int offsetField;

    private bool offsetFieldSpecified;

    private byte precision1Field;

    private bool precision1FieldSpecified;

    private byte scale1Field;

    private bool scale1FieldSpecified;

    private SqlDbType sqlDbTypeField;

    private bool sqlDbTypeFieldSpecified;

    private object sqlValueField;

    private string typeNameField;

    private string udtTypeNameField;

    private string xmlSchemaCollectionDatabaseField;

    private string xmlSchemaCollectionNameField;

    private string xmlSchemaCollectionOwningSchemaField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public SqlCompareOptions CompareInfo
    {
        get
        {
            return this.compareInfoField;
        }
        set
        {
            this.compareInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CompareInfoSpecified
    {
        get
        {
            return this.compareInfoFieldSpecified;
        }
        set
        {
            this.compareInfoFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public int LocaleId
    {
        get
        {
            return this.localeIdField;
        }
        set
        {
            this.localeIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LocaleIdSpecified
    {
        get
        {
            return this.localeIdFieldSpecified;
        }
        set
        {
            this.localeIdFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int Offset
    {
        get
        {
            return this.offsetField;
        }
        set
        {
            this.offsetField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OffsetSpecified
    {
        get
        {
            return this.offsetFieldSpecified;
        }
        set
        {
            this.offsetFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Precision", Order = 3)]
    public byte Precision1
    {
        get
        {
            return this.precision1Field;
        }
        set
        {
            this.precision1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Precision1Specified
    {
        get
        {
            return this.precision1FieldSpecified;
        }
        set
        {
            this.precision1FieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Scale", Order = 4)]
    public byte Scale1
    {
        get
        {
            return this.scale1Field;
        }
        set
        {
            this.scale1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Scale1Specified
    {
        get
        {
            return this.scale1FieldSpecified;
        }
        set
        {
            this.scale1FieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public SqlDbType SqlDbType
    {
        get
        {
            return this.sqlDbTypeField;
        }
        set
        {
            this.sqlDbTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SqlDbTypeSpecified
    {
        get
        {
            return this.sqlDbTypeFieldSpecified;
        }
        set
        {
            this.sqlDbTypeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
    public object SqlValue
    {
        get
        {
            return this.sqlValueField;
        }
        set
        {
            this.sqlValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
    public string TypeName
    {
        get
        {
            return this.typeNameField;
        }
        set
        {
            this.typeNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 8)]
    public string UdtTypeName
    {
        get
        {
            return this.udtTypeNameField;
        }
        set
        {
            this.udtTypeNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 9)]
    public string XmlSchemaCollectionDatabase
    {
        get
        {
            return this.xmlSchemaCollectionDatabaseField;
        }
        set
        {
            this.xmlSchemaCollectionDatabaseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
    public string XmlSchemaCollectionName
    {
        get
        {
            return this.xmlSchemaCollectionNameField;
        }
        set
        {
            this.xmlSchemaCollectionNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 11)]
    public string XmlSchemaCollectionOwningSchema
    {
        get
        {
            return this.xmlSchemaCollectionOwningSchemaField;
        }
        set
        {
            this.xmlSchemaCollectionOwningSchemaField = value;
        }
    }
}

/// <remarks/>
[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System.Data.SqlTypes")]
public enum SqlCompareOptions
{

    /// <remarks/>
    None = 1,

    /// <remarks/>
    IgnoreCase = 2,

    /// <remarks/>
    IgnoreNonSpace = 4,

    /// <remarks/>
    IgnoreKanaType = 8,

    /// <remarks/>
    IgnoreWidth = 16,

    /// <remarks/>
    BinarySort = 32,

    /// <remarks/>
    BinarySort2 = 64,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System.Data")]
public enum SqlDbType
{

    /// <remarks/>
    BigInt,

    /// <remarks/>
    Binary,

    /// <remarks/>
    Bit,

    /// <remarks/>
    Char,

    /// <remarks/>
    DateTime,

    /// <remarks/>
    Decimal,

    /// <remarks/>
    Float,

    /// <remarks/>
    Image,

    /// <remarks/>
    Int,

    /// <remarks/>
    Money,

    /// <remarks/>
    NChar,

    /// <remarks/>
    NText,

    /// <remarks/>
    NVarChar,

    /// <remarks/>
    Real,

    /// <remarks/>
    UniqueIdentifier,

    /// <remarks/>
    SmallDateTime,

    /// <remarks/>
    SmallInt,

    /// <remarks/>
    SmallMoney,

    /// <remarks/>
    Text,

    /// <remarks/>
    Timestamp,

    /// <remarks/>
    TinyInt,

    /// <remarks/>
    VarBinary,

    /// <remarks/>
    VarChar,

    /// <remarks/>
    Variant,

    /// <remarks/>
    Xml,

    /// <remarks/>
    Udt,

    /// <remarks/>
    Structured,

    /// <remarks/>
    Date,

    /// <remarks/>
    Time,

    /// <remarks/>
    DateTime2,

    /// <remarks/>
    DateTimeOffset,
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteDataSet", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteDataSetRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string commandText;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerService")]
    public SQLParameter[] dsparams;

    public ExecuteDataSetRequest()
    {
    }

    public ExecuteDataSetRequest(string commandText, SQLParameter[] dsparams)
    {
        this.commandText = commandText;
        this.dsparams = dsparams;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteDataSetResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteDataSetResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataSet ExecuteDataSetResult;

    public ExecuteDataSetResponse()
    {
    }

    public ExecuteDataSetResponse(System.Data.DataSet ExecuteDataSetResult)
    {
        this.ExecuteDataSetResult = ExecuteDataSetResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteNonQueryOutput", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteNonQueryOutputRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string commandText;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerService")]
    public SQLParameter[] nonparams;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public object output;

    public ExecuteNonQueryOutputRequest()
    {
    }

    public ExecuteNonQueryOutputRequest(string commandText, SQLParameter[] nonparams, object output)
    {
        this.commandText = commandText;
        this.nonparams = nonparams;
        this.output = output;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteNonQueryOutputResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteNonQueryOutputResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteNonQueryOutputResult;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public object output;

    public ExecuteNonQueryOutputResponse()
    {
    }

    public ExecuteNonQueryOutputResponse(int ExecuteNonQueryOutputResult, object output)
    {
        this.ExecuteNonQueryOutputResult = ExecuteNonQueryOutputResult;
        this.output = output;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteNonQuery", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteNonQueryRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string commandText;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerService")]
    public SQLParameter[] nonparams;

    public ExecuteNonQueryRequest()
    {
    }

    public ExecuteNonQueryRequest(string commandText, SQLParameter[] nonparams)
    {
        this.commandText = commandText;
        this.nonparams = nonparams;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteNonQueryResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteNonQueryResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteNonQueryResult;

    public ExecuteNonQueryResponse()
    {
    }

    public ExecuteNonQueryResponse(int ExecuteNonQueryResult)
    {
        this.ExecuteNonQueryResult = ExecuteNonQueryResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteScalar", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteScalarRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string commandText;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerService")]
    public SQLParameter[] nonparams;

    public ExecuteScalarRequest()
    {
    }

    public ExecuteScalarRequest(string commandText, SQLParameter[] nonparams)
    {
        this.commandText = commandText;
        this.nonparams = nonparams;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteScalarResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteScalarResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public object ExecuteScalarResult;

    public ExecuteScalarResponse()
    {
    }

    public ExecuteScalarResponse(object ExecuteScalarResult)
    {
        this.ExecuteScalarResult = ExecuteScalarResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDALServiceChannel : IDALService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DALServiceClient : System.ServiceModel.ClientBase<IDALService>, IDALService
{

    public DALServiceClient()
    {
    }

    public DALServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public DALServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public DALServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public DALServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteDataSetResponse IDALService.ExecuteDataSet(ExecuteDataSetRequest request)
    {
        return base.Channel.ExecuteDataSet(request);
    }

    public System.Data.DataSet ExecuteDataSet(string commandText, SQLParameter[] dsparams)
    {
        ExecuteDataSetRequest inValue = new ExecuteDataSetRequest();
        inValue.commandText = commandText;
        inValue.dsparams = dsparams;
        ExecuteDataSetResponse retVal = ((IDALService)(this)).ExecuteDataSet(inValue);
        return retVal.ExecuteDataSetResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ExecuteDataSetResponse> IDALService.ExecuteDataSetAsync(ExecuteDataSetRequest request)
    {
        return base.Channel.ExecuteDataSetAsync(request);
    }

    public System.Threading.Tasks.Task<ExecuteDataSetResponse> ExecuteDataSetAsync(string commandText, SQLParameter[] dsparams)
    {
        ExecuteDataSetRequest inValue = new ExecuteDataSetRequest();
        inValue.commandText = commandText;
        inValue.dsparams = dsparams;
        return ((IDALService)(this)).ExecuteDataSetAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteNonQueryOutputResponse IDALService.ExecuteNonQueryOutput(ExecuteNonQueryOutputRequest request)
    {
        return base.Channel.ExecuteNonQueryOutput(request);
    }

    public int ExecuteNonQueryOutput(string commandText, SQLParameter[] nonparams, ref object output)
    {
        ExecuteNonQueryOutputRequest inValue = new ExecuteNonQueryOutputRequest();
        inValue.commandText = commandText;
        inValue.nonparams = nonparams;
        inValue.output = output;
        ExecuteNonQueryOutputResponse retVal = ((IDALService)(this)).ExecuteNonQueryOutput(inValue);
        output = retVal.output;
        return retVal.ExecuteNonQueryOutputResult;
    }

    public System.Threading.Tasks.Task<ExecuteNonQueryOutputResponse> ExecuteNonQueryOutputAsync(ExecuteNonQueryOutputRequest request)
    {
        return base.Channel.ExecuteNonQueryOutputAsync(request);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteNonQueryResponse IDALService.ExecuteNonQuery(ExecuteNonQueryRequest request)
    {
        return base.Channel.ExecuteNonQuery(request);
    }

    public int ExecuteNonQuery(string commandText, SQLParameter[] nonparams)
    {
        ExecuteNonQueryRequest inValue = new ExecuteNonQueryRequest();
        inValue.commandText = commandText;
        inValue.nonparams = nonparams;
        ExecuteNonQueryResponse retVal = ((IDALService)(this)).ExecuteNonQuery(inValue);
        return retVal.ExecuteNonQueryResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ExecuteNonQueryResponse> IDALService.ExecuteNonQueryAsync(ExecuteNonQueryRequest request)
    {
        return base.Channel.ExecuteNonQueryAsync(request);
    }

    public System.Threading.Tasks.Task<ExecuteNonQueryResponse> ExecuteNonQueryAsync(string commandText, SQLParameter[] nonparams)
    {
        ExecuteNonQueryRequest inValue = new ExecuteNonQueryRequest();
        inValue.commandText = commandText;
        inValue.nonparams = nonparams;
        return ((IDALService)(this)).ExecuteNonQueryAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteScalarResponse IDALService.ExecuteScalar(ExecuteScalarRequest request)
    {
        return base.Channel.ExecuteScalar(request);
    }

    public object ExecuteScalar(string commandText, SQLParameter[] nonparams)
    {
        ExecuteScalarRequest inValue = new ExecuteScalarRequest();
        inValue.commandText = commandText;
        inValue.nonparams = nonparams;
        ExecuteScalarResponse retVal = ((IDALService)(this)).ExecuteScalar(inValue);
        return retVal.ExecuteScalarResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ExecuteScalarResponse> IDALService.ExecuteScalarAsync(ExecuteScalarRequest request)
    {
        return base.Channel.ExecuteScalarAsync(request);
    }

    public System.Threading.Tasks.Task<ExecuteScalarResponse> ExecuteScalarAsync(string commandText, SQLParameter[] nonparams)
    {
        ExecuteScalarRequest inValue = new ExecuteScalarRequest();
        inValue.commandText = commandText;
        inValue.nonparams = nonparams;
        return ((IDALService)(this)).ExecuteScalarAsync(inValue);
    }
}
