//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableTransformationLayer.ABBConnectServiceRef {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetHumanInformation_Result", Namespace="http://schemas.datacontract.org/2004/07/ABBJSONService")]
    public partial class GetHumanInformation_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string LocationField;
        
        private string NameField;
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetHumanInformationByUsername_Result", Namespace="http://schemas.datacontract.org/2004/07/ABBJSONService")]
    public partial class GetHumanInformationByUsername_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        private string LocationField;
        
        private string NameField;
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLatestXFeeds_Result", Namespace="http://schemas.datacontract.org/2004/07/ABBJSONService")]
    public partial class GetLatestXFeeds_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime CreationTimeStampField;
        
        private int FeedIdField;
        
        private string FilePathField;
        
        private string LocationField;
        
        private string PrioCategoryField;
        
        private int PrioValueField;
        
        private string TextField;
        
        private string TypeField;
        
        private int UserIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTimeStamp {
            get {
                return this.CreationTimeStampField;
            }
            set {
                if ((this.CreationTimeStampField.Equals(value) != true)) {
                    this.CreationTimeStampField = value;
                    this.RaisePropertyChanged("CreationTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeedId {
            get {
                return this.FeedIdField;
            }
            set {
                if ((this.FeedIdField.Equals(value) != true)) {
                    this.FeedIdField = value;
                    this.RaisePropertyChanged("FeedId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrioCategory {
            get {
                return this.PrioCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioCategoryField, value) != true)) {
                    this.PrioCategoryField = value;
                    this.RaisePropertyChanged("PrioCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrioValue {
            get {
                return this.PrioValueField;
            }
            set {
                if ((this.PrioValueField.Equals(value) != true)) {
                    this.PrioValueField = value;
                    this.RaisePropertyChanged("PrioValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLatestXFeedsFromId_Result", Namespace="http://schemas.datacontract.org/2004/07/ABBJSONService")]
    public partial class GetLatestXFeedsFromId_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime CreationTimeStampField;
        
        private int FeedIdField;
        
        private string FilePathField;
        
        private string LocationField;
        
        private string PrioCategoryField;
        
        private int PrioValueField;
        
        private string TextField;
        
        private string TypeField;
        
        private int UserIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTimeStamp {
            get {
                return this.CreationTimeStampField;
            }
            set {
                if ((this.CreationTimeStampField.Equals(value) != true)) {
                    this.CreationTimeStampField = value;
                    this.RaisePropertyChanged("CreationTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeedId {
            get {
                return this.FeedIdField;
            }
            set {
                if ((this.FeedIdField.Equals(value) != true)) {
                    this.FeedIdField = value;
                    this.RaisePropertyChanged("FeedId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrioCategory {
            get {
                return this.PrioCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioCategoryField, value) != true)) {
                    this.PrioCategoryField = value;
                    this.RaisePropertyChanged("PrioCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrioValue {
            get {
                return this.PrioValueField;
            }
            set {
                if ((this.PrioValueField.Equals(value) != true)) {
                    this.PrioValueField = value;
                    this.RaisePropertyChanged("PrioValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPriorityCategories_Result", Namespace="http://schemas.datacontract.org/2004/07/ABBJSONService")]
    public partial class GetPriorityCategories_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFeedComments_Result", Namespace="http://schemas.datacontract.org/2004/07/ABBJSONService")]
    public partial class GetFeedComments_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CommentTextField;
        
        private System.DateTime CreationTimeStampField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentText {
            get {
                return this.CommentTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentTextField, value) != true)) {
                    this.CommentTextField = value;
                    this.RaisePropertyChanged("CommentText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTimeStamp {
            get {
                return this.CreationTimeStampField;
            }
            set {
                if ((this.CreationTimeStampField.Equals(value) != true)) {
                    this.CreationTimeStampField = value;
                    this.RaisePropertyChanged("CreationTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFeedTags_Result", Namespace="http://schemas.datacontract.org/2004/07/ABBJSONService")]
    public partial class GetFeedTags_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private int UserIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABBConnectServiceRef.IABBConnectWCF")]
    public interface IABBConnectWCF {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/LogIn", ReplyAction="http://tempuri.org/IABBConnectWCF/LogInResponse")]
        System.IAsyncResult BeginLogIn(string username, string password, System.AsyncCallback callback, object asyncState);
        
        bool EndLogIn(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/GetHumanInformation", ReplyAction="http://tempuri.org/IABBConnectWCF/GetHumanInformationResponse")]
        System.IAsyncResult BeginGetHumanInformation(string id, System.AsyncCallback callback, object asyncState);
        
        PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformation_Result EndGetHumanInformation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/GetHumanInformationByUsername", ReplyAction="http://tempuri.org/IABBConnectWCF/GetHumanInformationByUsernameResponse")]
        System.IAsyncResult BeginGetHumanInformationByUsername(string username, System.AsyncCallback callback, object asyncState);
        
        PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformationByUsername_Result EndGetHumanInformationByUsername(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/GetLatestXFeeds", ReplyAction="http://tempuri.org/IABBConnectWCF/GetLatestXFeedsResponse")]
        System.IAsyncResult BeginGetLatestXFeeds(string X, System.AsyncCallback callback, object asyncState);
        
        PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeeds_Result[] EndGetLatestXFeeds(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/GetLatestXFeedsFromId", ReplyAction="http://tempuri.org/IABBConnectWCF/GetLatestXFeedsFromIdResponse")]
        System.IAsyncResult BeginGetLatestXFeedsFromId(string X, string Id, System.AsyncCallback callback, object asyncState);
        
        PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeedsFromId_Result[] EndGetLatestXFeedsFromId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/PostFeed", ReplyAction="http://tempuri.org/IABBConnectWCF/PostFeedResponse")]
        System.IAsyncResult BeginPostFeed(string id, string text, string filepath, string prioId, System.AsyncCallback callback, object asyncState);
        
        int EndPostFeed(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/GetCategories", ReplyAction="http://tempuri.org/IABBConnectWCF/GetCategoriesResponse")]
        System.IAsyncResult BeginGetCategories(System.AsyncCallback callback, object asyncState);
        
        PortableTransformationLayer.ABBConnectServiceRef.GetPriorityCategories_Result[] EndGetCategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/GetFeedComments", ReplyAction="http://tempuri.org/IABBConnectWCF/GetFeedCommentsResponse")]
        System.IAsyncResult BeginGetFeedComments(string feedId, System.AsyncCallback callback, object asyncState);
        
        PortableTransformationLayer.ABBConnectServiceRef.GetFeedComments_Result[] EndGetFeedComments(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IABBConnectWCF/GetFeedTags", ReplyAction="http://tempuri.org/IABBConnectWCF/GetFeedTagsResponse")]
        System.IAsyncResult BeginGetFeedTags(string feedId, System.AsyncCallback callback, object asyncState);
        
        PortableTransformationLayer.ABBConnectServiceRef.GetFeedTags_Result[] EndGetFeedTags(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABBConnectWCFChannel : PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHumanInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHumanInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformation_Result Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformation_Result)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHumanInformationByUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHumanInformationByUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformationByUsername_Result Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformationByUsername_Result)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLatestXFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLatestXFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeeds_Result[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeeds_Result[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLatestXFeedsFromIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLatestXFeedsFromIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeedsFromId_Result[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeedsFromId_Result[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PostFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PortableTransformationLayer.ABBConnectServiceRef.GetPriorityCategories_Result[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PortableTransformationLayer.ABBConnectServiceRef.GetPriorityCategories_Result[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFeedCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFeedCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PortableTransformationLayer.ABBConnectServiceRef.GetFeedComments_Result[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PortableTransformationLayer.ABBConnectServiceRef.GetFeedComments_Result[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFeedTagsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFeedTagsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PortableTransformationLayer.ABBConnectServiceRef.GetFeedTags_Result[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PortableTransformationLayer.ABBConnectServiceRef.GetFeedTags_Result[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABBConnectWCFClient : System.ServiceModel.ClientBase<PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF>, PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF {
        
        private BeginOperationDelegate onBeginLogInDelegate;
        
        private EndOperationDelegate onEndLogInDelegate;
        
        private System.Threading.SendOrPostCallback onLogInCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHumanInformationDelegate;
        
        private EndOperationDelegate onEndGetHumanInformationDelegate;
        
        private System.Threading.SendOrPostCallback onGetHumanInformationCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHumanInformationByUsernameDelegate;
        
        private EndOperationDelegate onEndGetHumanInformationByUsernameDelegate;
        
        private System.Threading.SendOrPostCallback onGetHumanInformationByUsernameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLatestXFeedsDelegate;
        
        private EndOperationDelegate onEndGetLatestXFeedsDelegate;
        
        private System.Threading.SendOrPostCallback onGetLatestXFeedsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLatestXFeedsFromIdDelegate;
        
        private EndOperationDelegate onEndGetLatestXFeedsFromIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetLatestXFeedsFromIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginPostFeedDelegate;
        
        private EndOperationDelegate onEndPostFeedDelegate;
        
        private System.Threading.SendOrPostCallback onPostFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCategoriesDelegate;
        
        private EndOperationDelegate onEndGetCategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFeedCommentsDelegate;
        
        private EndOperationDelegate onEndGetFeedCommentsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFeedCommentsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFeedTagsDelegate;
        
        private EndOperationDelegate onEndGetFeedTagsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFeedTagsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ABBConnectWCFClient(EndpointConfiguration endpointConfiguration) : 
                base(ABBConnectWCFClient.GetBindingForEndpoint(endpointConfiguration), ABBConnectWCFClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public ABBConnectWCFClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ABBConnectWCFClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public ABBConnectWCFClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ABBConnectWCFClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public ABBConnectWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LogInCompletedEventArgs> LogInCompleted;
        
        public event System.EventHandler<GetHumanInformationCompletedEventArgs> GetHumanInformationCompleted;
        
        public event System.EventHandler<GetHumanInformationByUsernameCompletedEventArgs> GetHumanInformationByUsernameCompleted;
        
        public event System.EventHandler<GetLatestXFeedsCompletedEventArgs> GetLatestXFeedsCompleted;
        
        public event System.EventHandler<GetLatestXFeedsFromIdCompletedEventArgs> GetLatestXFeedsFromIdCompleted;
        
        public event System.EventHandler<PostFeedCompletedEventArgs> PostFeedCompleted;
        
        public event System.EventHandler<GetCategoriesCompletedEventArgs> GetCategoriesCompleted;
        
        public event System.EventHandler<GetFeedCommentsCompletedEventArgs> GetFeedCommentsCompleted;
        
        public event System.EventHandler<GetFeedTagsCompletedEventArgs> GetFeedTagsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginLogIn(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogIn(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndLogIn(System.IAsyncResult result) {
            return base.Channel.EndLogIn(result);
        }
        
        private System.IAsyncResult OnBeginLogIn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginLogIn(username, password, callback, asyncState);
        }
        
        private object[] OnEndLogIn(System.IAsyncResult result) {
            bool retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndLogIn(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLogInCompleted(object state) {
            if ((this.LogInCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogInCompleted(this, new LogInCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogInAsync(string username, string password) {
            this.LogInAsync(username, password, null);
        }
        
        public void LogInAsync(string username, string password, object userState) {
            if ((this.onBeginLogInDelegate == null)) {
                this.onBeginLogInDelegate = new BeginOperationDelegate(this.OnBeginLogIn);
            }
            if ((this.onEndLogInDelegate == null)) {
                this.onEndLogInDelegate = new EndOperationDelegate(this.OnEndLogIn);
            }
            if ((this.onLogInCompletedDelegate == null)) {
                this.onLogInCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogInCompleted);
            }
            base.InvokeAsync(this.onBeginLogInDelegate, new object[] {
                        username,
                        password}, this.onEndLogInDelegate, this.onLogInCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginGetHumanInformation(string id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHumanInformation(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformation_Result PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndGetHumanInformation(System.IAsyncResult result) {
            return base.Channel.EndGetHumanInformation(result);
        }
        
        private System.IAsyncResult OnBeginGetHumanInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginGetHumanInformation(id, callback, asyncState);
        }
        
        private object[] OnEndGetHumanInformation(System.IAsyncResult result) {
            PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformation_Result retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndGetHumanInformation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHumanInformationCompleted(object state) {
            if ((this.GetHumanInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHumanInformationCompleted(this, new GetHumanInformationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHumanInformationAsync(string id) {
            this.GetHumanInformationAsync(id, null);
        }
        
        public void GetHumanInformationAsync(string id, object userState) {
            if ((this.onBeginGetHumanInformationDelegate == null)) {
                this.onBeginGetHumanInformationDelegate = new BeginOperationDelegate(this.OnBeginGetHumanInformation);
            }
            if ((this.onEndGetHumanInformationDelegate == null)) {
                this.onEndGetHumanInformationDelegate = new EndOperationDelegate(this.OnEndGetHumanInformation);
            }
            if ((this.onGetHumanInformationCompletedDelegate == null)) {
                this.onGetHumanInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHumanInformationCompleted);
            }
            base.InvokeAsync(this.onBeginGetHumanInformationDelegate, new object[] {
                        id}, this.onEndGetHumanInformationDelegate, this.onGetHumanInformationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginGetHumanInformationByUsername(string username, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHumanInformationByUsername(username, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformationByUsername_Result PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndGetHumanInformationByUsername(System.IAsyncResult result) {
            return base.Channel.EndGetHumanInformationByUsername(result);
        }
        
        private System.IAsyncResult OnBeginGetHumanInformationByUsername(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginGetHumanInformationByUsername(username, callback, asyncState);
        }
        
        private object[] OnEndGetHumanInformationByUsername(System.IAsyncResult result) {
            PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformationByUsername_Result retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndGetHumanInformationByUsername(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHumanInformationByUsernameCompleted(object state) {
            if ((this.GetHumanInformationByUsernameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHumanInformationByUsernameCompleted(this, new GetHumanInformationByUsernameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHumanInformationByUsernameAsync(string username) {
            this.GetHumanInformationByUsernameAsync(username, null);
        }
        
        public void GetHumanInformationByUsernameAsync(string username, object userState) {
            if ((this.onBeginGetHumanInformationByUsernameDelegate == null)) {
                this.onBeginGetHumanInformationByUsernameDelegate = new BeginOperationDelegate(this.OnBeginGetHumanInformationByUsername);
            }
            if ((this.onEndGetHumanInformationByUsernameDelegate == null)) {
                this.onEndGetHumanInformationByUsernameDelegate = new EndOperationDelegate(this.OnEndGetHumanInformationByUsername);
            }
            if ((this.onGetHumanInformationByUsernameCompletedDelegate == null)) {
                this.onGetHumanInformationByUsernameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHumanInformationByUsernameCompleted);
            }
            base.InvokeAsync(this.onBeginGetHumanInformationByUsernameDelegate, new object[] {
                        username}, this.onEndGetHumanInformationByUsernameDelegate, this.onGetHumanInformationByUsernameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginGetLatestXFeeds(string X, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLatestXFeeds(X, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeeds_Result[] PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndGetLatestXFeeds(System.IAsyncResult result) {
            return base.Channel.EndGetLatestXFeeds(result);
        }
        
        private System.IAsyncResult OnBeginGetLatestXFeeds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string X = ((string)(inValues[0]));
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginGetLatestXFeeds(X, callback, asyncState);
        }
        
        private object[] OnEndGetLatestXFeeds(System.IAsyncResult result) {
            PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeeds_Result[] retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndGetLatestXFeeds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLatestXFeedsCompleted(object state) {
            if ((this.GetLatestXFeedsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLatestXFeedsCompleted(this, new GetLatestXFeedsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLatestXFeedsAsync(string X) {
            this.GetLatestXFeedsAsync(X, null);
        }
        
        public void GetLatestXFeedsAsync(string X, object userState) {
            if ((this.onBeginGetLatestXFeedsDelegate == null)) {
                this.onBeginGetLatestXFeedsDelegate = new BeginOperationDelegate(this.OnBeginGetLatestXFeeds);
            }
            if ((this.onEndGetLatestXFeedsDelegate == null)) {
                this.onEndGetLatestXFeedsDelegate = new EndOperationDelegate(this.OnEndGetLatestXFeeds);
            }
            if ((this.onGetLatestXFeedsCompletedDelegate == null)) {
                this.onGetLatestXFeedsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLatestXFeedsCompleted);
            }
            base.InvokeAsync(this.onBeginGetLatestXFeedsDelegate, new object[] {
                        X}, this.onEndGetLatestXFeedsDelegate, this.onGetLatestXFeedsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginGetLatestXFeedsFromId(string X, string Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLatestXFeedsFromId(X, Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeedsFromId_Result[] PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndGetLatestXFeedsFromId(System.IAsyncResult result) {
            return base.Channel.EndGetLatestXFeedsFromId(result);
        }
        
        private System.IAsyncResult OnBeginGetLatestXFeedsFromId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string X = ((string)(inValues[0]));
            string Id = ((string)(inValues[1]));
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginGetLatestXFeedsFromId(X, Id, callback, asyncState);
        }
        
        private object[] OnEndGetLatestXFeedsFromId(System.IAsyncResult result) {
            PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeedsFromId_Result[] retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndGetLatestXFeedsFromId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLatestXFeedsFromIdCompleted(object state) {
            if ((this.GetLatestXFeedsFromIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLatestXFeedsFromIdCompleted(this, new GetLatestXFeedsFromIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLatestXFeedsFromIdAsync(string X, string Id) {
            this.GetLatestXFeedsFromIdAsync(X, Id, null);
        }
        
        public void GetLatestXFeedsFromIdAsync(string X, string Id, object userState) {
            if ((this.onBeginGetLatestXFeedsFromIdDelegate == null)) {
                this.onBeginGetLatestXFeedsFromIdDelegate = new BeginOperationDelegate(this.OnBeginGetLatestXFeedsFromId);
            }
            if ((this.onEndGetLatestXFeedsFromIdDelegate == null)) {
                this.onEndGetLatestXFeedsFromIdDelegate = new EndOperationDelegate(this.OnEndGetLatestXFeedsFromId);
            }
            if ((this.onGetLatestXFeedsFromIdCompletedDelegate == null)) {
                this.onGetLatestXFeedsFromIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLatestXFeedsFromIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetLatestXFeedsFromIdDelegate, new object[] {
                        X,
                        Id}, this.onEndGetLatestXFeedsFromIdDelegate, this.onGetLatestXFeedsFromIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginPostFeed(string id, string text, string filepath, string prioId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPostFeed(id, text, filepath, prioId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndPostFeed(System.IAsyncResult result) {
            return base.Channel.EndPostFeed(result);
        }
        
        private System.IAsyncResult OnBeginPostFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            string text = ((string)(inValues[1]));
            string filepath = ((string)(inValues[2]));
            string prioId = ((string)(inValues[3]));
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginPostFeed(id, text, filepath, prioId, callback, asyncState);
        }
        
        private object[] OnEndPostFeed(System.IAsyncResult result) {
            int retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndPostFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPostFeedCompleted(object state) {
            if ((this.PostFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostFeedCompleted(this, new PostFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostFeedAsync(string id, string text, string filepath, string prioId) {
            this.PostFeedAsync(id, text, filepath, prioId, null);
        }
        
        public void PostFeedAsync(string id, string text, string filepath, string prioId, object userState) {
            if ((this.onBeginPostFeedDelegate == null)) {
                this.onBeginPostFeedDelegate = new BeginOperationDelegate(this.OnBeginPostFeed);
            }
            if ((this.onEndPostFeedDelegate == null)) {
                this.onEndPostFeedDelegate = new EndOperationDelegate(this.OnEndPostFeed);
            }
            if ((this.onPostFeedCompletedDelegate == null)) {
                this.onPostFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostFeedCompleted);
            }
            base.InvokeAsync(this.onBeginPostFeedDelegate, new object[] {
                        id,
                        text,
                        filepath,
                        prioId}, this.onEndPostFeedDelegate, this.onPostFeedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginGetCategories(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCategories(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortableTransformationLayer.ABBConnectServiceRef.GetPriorityCategories_Result[] PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndGetCategories(System.IAsyncResult result) {
            return base.Channel.EndGetCategories(result);
        }
        
        private System.IAsyncResult OnBeginGetCategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginGetCategories(callback, asyncState);
        }
        
        private object[] OnEndGetCategories(System.IAsyncResult result) {
            PortableTransformationLayer.ABBConnectServiceRef.GetPriorityCategories_Result[] retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndGetCategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCategoriesCompleted(object state) {
            if ((this.GetCategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCategoriesCompleted(this, new GetCategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCategoriesAsync() {
            this.GetCategoriesAsync(null);
        }
        
        public void GetCategoriesAsync(object userState) {
            if ((this.onBeginGetCategoriesDelegate == null)) {
                this.onBeginGetCategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetCategories);
            }
            if ((this.onEndGetCategoriesDelegate == null)) {
                this.onEndGetCategoriesDelegate = new EndOperationDelegate(this.OnEndGetCategories);
            }
            if ((this.onGetCategoriesCompletedDelegate == null)) {
                this.onGetCategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCategoriesDelegate, null, this.onEndGetCategoriesDelegate, this.onGetCategoriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginGetFeedComments(string feedId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFeedComments(feedId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortableTransformationLayer.ABBConnectServiceRef.GetFeedComments_Result[] PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndGetFeedComments(System.IAsyncResult result) {
            return base.Channel.EndGetFeedComments(result);
        }
        
        private System.IAsyncResult OnBeginGetFeedComments(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string feedId = ((string)(inValues[0]));
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginGetFeedComments(feedId, callback, asyncState);
        }
        
        private object[] OnEndGetFeedComments(System.IAsyncResult result) {
            PortableTransformationLayer.ABBConnectServiceRef.GetFeedComments_Result[] retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndGetFeedComments(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFeedCommentsCompleted(object state) {
            if ((this.GetFeedCommentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFeedCommentsCompleted(this, new GetFeedCommentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFeedCommentsAsync(string feedId) {
            this.GetFeedCommentsAsync(feedId, null);
        }
        
        public void GetFeedCommentsAsync(string feedId, object userState) {
            if ((this.onBeginGetFeedCommentsDelegate == null)) {
                this.onBeginGetFeedCommentsDelegate = new BeginOperationDelegate(this.OnBeginGetFeedComments);
            }
            if ((this.onEndGetFeedCommentsDelegate == null)) {
                this.onEndGetFeedCommentsDelegate = new EndOperationDelegate(this.OnEndGetFeedComments);
            }
            if ((this.onGetFeedCommentsCompletedDelegate == null)) {
                this.onGetFeedCommentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFeedCommentsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFeedCommentsDelegate, new object[] {
                        feedId}, this.onEndGetFeedCommentsDelegate, this.onGetFeedCommentsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.BeginGetFeedTags(string feedId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFeedTags(feedId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortableTransformationLayer.ABBConnectServiceRef.GetFeedTags_Result[] PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF.EndGetFeedTags(System.IAsyncResult result) {
            return base.Channel.EndGetFeedTags(result);
        }
        
        private System.IAsyncResult OnBeginGetFeedTags(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string feedId = ((string)(inValues[0]));
            return ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).BeginGetFeedTags(feedId, callback, asyncState);
        }
        
        private object[] OnEndGetFeedTags(System.IAsyncResult result) {
            PortableTransformationLayer.ABBConnectServiceRef.GetFeedTags_Result[] retVal = ((PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF)(this)).EndGetFeedTags(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFeedTagsCompleted(object state) {
            if ((this.GetFeedTagsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFeedTagsCompleted(this, new GetFeedTagsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFeedTagsAsync(string feedId) {
            this.GetFeedTagsAsync(feedId, null);
        }
        
        public void GetFeedTagsAsync(string feedId, object userState) {
            if ((this.onBeginGetFeedTagsDelegate == null)) {
                this.onBeginGetFeedTagsDelegate = new BeginOperationDelegate(this.OnBeginGetFeedTags);
            }
            if ((this.onEndGetFeedTagsDelegate == null)) {
                this.onEndGetFeedTagsDelegate = new EndOperationDelegate(this.OnEndGetFeedTags);
            }
            if ((this.onGetFeedTagsCompletedDelegate == null)) {
                this.onGetFeedTagsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFeedTagsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFeedTagsDelegate, new object[] {
                        feedId}, this.onEndGetFeedTagsDelegate, this.onGetFeedTagsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF CreateChannel() {
            return new ABBConnectWCFClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private class ABBConnectWCFClientChannel : ChannelBase<PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF>, PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF {
            
            public ABBConnectWCFClientChannel(System.ServiceModel.ClientBase<PortableTransformationLayer.ABBConnectServiceRef.IABBConnectWCF> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogIn(string username, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("LogIn", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndLogIn(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("LogIn", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetHumanInformation(string id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetHumanInformation", _args, callback, asyncState);
                return _result;
            }
            
            public PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformation_Result EndGetHumanInformation(System.IAsyncResult result) {
                object[] _args = new object[0];
                PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformation_Result _result = ((PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformation_Result)(base.EndInvoke("GetHumanInformation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetHumanInformationByUsername(string username, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = username;
                System.IAsyncResult _result = base.BeginInvoke("GetHumanInformationByUsername", _args, callback, asyncState);
                return _result;
            }
            
            public PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformationByUsername_Result EndGetHumanInformationByUsername(System.IAsyncResult result) {
                object[] _args = new object[0];
                PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformationByUsername_Result _result = ((PortableTransformationLayer.ABBConnectServiceRef.GetHumanInformationByUsername_Result)(base.EndInvoke("GetHumanInformationByUsername", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLatestXFeeds(string X, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = X;
                System.IAsyncResult _result = base.BeginInvoke("GetLatestXFeeds", _args, callback, asyncState);
                return _result;
            }
            
            public PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeeds_Result[] EndGetLatestXFeeds(System.IAsyncResult result) {
                object[] _args = new object[0];
                PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeeds_Result[] _result = ((PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeeds_Result[])(base.EndInvoke("GetLatestXFeeds", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLatestXFeedsFromId(string X, string Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = X;
                _args[1] = Id;
                System.IAsyncResult _result = base.BeginInvoke("GetLatestXFeedsFromId", _args, callback, asyncState);
                return _result;
            }
            
            public PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeedsFromId_Result[] EndGetLatestXFeedsFromId(System.IAsyncResult result) {
                object[] _args = new object[0];
                PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeedsFromId_Result[] _result = ((PortableTransformationLayer.ABBConnectServiceRef.GetLatestXFeedsFromId_Result[])(base.EndInvoke("GetLatestXFeedsFromId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPostFeed(string id, string text, string filepath, string prioId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = id;
                _args[1] = text;
                _args[2] = filepath;
                _args[3] = prioId;
                System.IAsyncResult _result = base.BeginInvoke("PostFeed", _args, callback, asyncState);
                return _result;
            }
            
            public int EndPostFeed(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("PostFeed", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCategories(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCategories", _args, callback, asyncState);
                return _result;
            }
            
            public PortableTransformationLayer.ABBConnectServiceRef.GetPriorityCategories_Result[] EndGetCategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                PortableTransformationLayer.ABBConnectServiceRef.GetPriorityCategories_Result[] _result = ((PortableTransformationLayer.ABBConnectServiceRef.GetPriorityCategories_Result[])(base.EndInvoke("GetCategories", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFeedComments(string feedId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = feedId;
                System.IAsyncResult _result = base.BeginInvoke("GetFeedComments", _args, callback, asyncState);
                return _result;
            }
            
            public PortableTransformationLayer.ABBConnectServiceRef.GetFeedComments_Result[] EndGetFeedComments(System.IAsyncResult result) {
                object[] _args = new object[0];
                PortableTransformationLayer.ABBConnectServiceRef.GetFeedComments_Result[] _result = ((PortableTransformationLayer.ABBConnectServiceRef.GetFeedComments_Result[])(base.EndInvoke("GetFeedComments", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFeedTags(string feedId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = feedId;
                System.IAsyncResult _result = base.BeginInvoke("GetFeedTags", _args, callback, asyncState);
                return _result;
            }
            
            public PortableTransformationLayer.ABBConnectServiceRef.GetFeedTags_Result[] EndGetFeedTags(System.IAsyncResult result) {
                object[] _args = new object[0];
                PortableTransformationLayer.ABBConnectServiceRef.GetFeedTags_Result[] _result = ((PortableTransformationLayer.ABBConnectServiceRef.GetFeedTags_Result[])(base.EndInvoke("GetFeedTags", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
        }
    }
}
